// <auto-generated />
using System;
using BlazorGame.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlazorGame.Api.Migrations
{
    [DbContext(typeof(AventureDbContext))]
    [Migration("20251127093703_V4_EstActif")]
    partial class V4_EstActif
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlazorGame.Domain.Administrateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Administrateurs");
                });

            modelBuilder.Entity("BlazorGame.Domain.Donjon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NombreDeSalles")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Donjons");
                });

            modelBuilder.Entity("BlazorGame.Domain.Joueur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AdministrateurId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DerniereConnexion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstActif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PeutReprendrePartie")
                        .HasColumnType("boolean");

                    b.Property<int>("ScoreTotal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdministrateurId");

                    b.ToTable("Joueurs");
                });

            modelBuilder.Entity("BlazorGame.Domain.Partie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DonjonId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EstTerminee")
                        .HasColumnType("boolean");

                    b.Property<Guid>("JoueurId")
                        .HasColumnType("uuid");

                    b.Property<int>("ScoreFinal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DonjonId");

                    b.HasIndex("JoueurId");

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("BlazorGame.Domain.Salle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ChoixFait")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("ChoixPossible")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("DonjonId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EstVisitee")
                        .HasColumnType("boolean");

                    b.Property<int>("ForceMonstre")
                        .HasColumnType("integer");

                    b.Property<string>("ImageMonstre")
                        .HasColumnType("text");

                    b.Property<int>("Niveau")
                        .HasColumnType("integer");

                    b.Property<string>("NomMonstre")
                        .HasColumnType("text");

                    b.Property<Guid>("PartieId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("PvMonstre")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DonjonId");

                    b.HasIndex("PartieId");

                    b.ToTable("Salles");
                });

            modelBuilder.Entity("BlazorGame.Domain.Joueur", b =>
                {
                    b.HasOne("BlazorGame.Domain.Administrateur", null)
                        .WithMany("JoueursSupervises")
                        .HasForeignKey("AdministrateurId");
                });

            modelBuilder.Entity("BlazorGame.Domain.Partie", b =>
                {
                    b.HasOne("BlazorGame.Domain.Donjon", "Donjon")
                        .WithMany("Parties")
                        .HasForeignKey("DonjonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorGame.Domain.Joueur", "Joueur")
                        .WithMany("Historique")
                        .HasForeignKey("JoueurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donjon");

                    b.Navigation("Joueur");
                });

            modelBuilder.Entity("BlazorGame.Domain.Salle", b =>
                {
                    b.HasOne("BlazorGame.Domain.Donjon", "Donjon")
                        .WithMany("Salles")
                        .HasForeignKey("DonjonId");

                    b.HasOne("BlazorGame.Domain.Partie", "Partie")
                        .WithMany("Salles")
                        .HasForeignKey("PartieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BlazorGame.Domain.ActionResultat", "Resultat", b1 =>
                        {
                            b1.Property<Guid>("SalleId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Action")
                                .HasColumnType("integer");

                            b1.Property<bool>("EstPiege")
                                .HasColumnType("boolean");

                            b1.Property<string>("Message")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Points")
                                .HasColumnType("integer");

                            b1.Property<int>("Risque")
                                .HasColumnType("integer");

                            b1.Property<int>("ScoreTotal")
                                .HasColumnType("integer");

                            b1.HasKey("SalleId");

                            b1.ToTable("Salles");

                            b1.WithOwner()
                                .HasForeignKey("SalleId");
                        });

                    b.Navigation("Donjon");

                    b.Navigation("Partie");

                    b.Navigation("Resultat");
                });

            modelBuilder.Entity("BlazorGame.Domain.Administrateur", b =>
                {
                    b.Navigation("JoueursSupervises");
                });

            modelBuilder.Entity("BlazorGame.Domain.Donjon", b =>
                {
                    b.Navigation("Parties");

                    b.Navigation("Salles");
                });

            modelBuilder.Entity("BlazorGame.Domain.Joueur", b =>
                {
                    b.Navigation("Historique");
                });

            modelBuilder.Entity("BlazorGame.Domain.Partie", b =>
                {
                    b.Navigation("Salles");
                });
#pragma warning restore 612, 618
        }
    }
}
